### PR TITLE
Refactor to use nan

### PR DESCRIPTION
**Pull request by achingbrain**
Refactors the C++ parts to use [rvagg/nan](http://github.com/rvagg/nan) for compatibility with io.js and node 0.12.  Also adds .gitignore file to ignore node_modules, build artefacts and other noise.

Cross reference: iojs/io.js#456

### CODE REVIEW

**Comment by usefulthink** [comment]
You are awesome! Thanks a lot for this, using nan was on my list for a while now and didn't have the time to figure out what needs to be changed to make it work. Will test it right away and merge if there are no problems.

**Comment by usefulthink** [comment]
works as intended, do you happen to know if this works with the arm-builds of iojs? I am curious if there need to be changes to the TypedArray-access in the C++-part for newer V8-versions.

**Comment by usefulthink** [comment]
just published a new version to npm.
Thanks for your help!

**Comment by achingbrain** [comment]
Using the provided arm6 build of io.js 1.4.2 I've got it working with a diode between a couple of ws2812s as per the [Adafruit wiring guide](https://learn.adafruit.com/neopixels-on-raspberry-pi/wiring) but I'm having problems using a [SparkFun logic level converter](https://www.sparkfun.com/products/12009) for more LEDs, although I'm probably using the wrong thing.  I've got a 74HCT125N on order to mirror your setup.

**Comment by achingbrain** [comment]
One thing I have noticed is that if you new up an Uint32Array with length 15 or under, it balks in the C++ code claiming it's not a Uint32Array.  This might be an internal node/io.js "optimisation" though.

**Comment by usefulthink** [comment]
never tried the diode-variant or anything else as i got it working from the start using the 74HCT125N. Do you have access to an oscilloscope to have a look at the signal coming out of the sparkfun llc?

**Comment by achingbrain** [comment]
Sadly no, just a multimeter.

**Comment by achingbrain** [comment]
Meh, actually I think I just had a loose wire or two, the llc seems to work fine.

**Pull request merged**
